CREATE TABLE IF NOT EXISTS mpa
(
    id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS genres
(
    id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS users
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255),
    login    VARCHAR(255),
    name     VARCHAR(255),
    birthday TIMESTAMP,
    deleted  BOOLEAN
);

CREATE TABLE IF NOT EXISTS users
(
    id       INT PRIMARY KEY AUTO_INCREMENT,
    email    VARCHAR(255),
    login    VARCHAR(255),
    name     VARCHAR(255),
    birthday TIMESTAMP,
    deleted  BOOLEAN
);


CREATE TABLE IF NOT EXISTS films
(
    id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255),
    description  VARCHAR(255),
    release_date TIMESTAMP,
    rate         INT,
    duration     INT,
    mpa_id       INT,
    FOREIGN KEY (mpa_id) REFERENCES mpa (id)
);

CREATE TABLE IF NOT EXISTS film_genres
(
    id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id   INT,
    genres_id INT,
    FOREIGN KEY (film_id) REFERENCES films (id),
    FOREIGN KEY (genres_id) REFERENCES genres (id)
);

CREATE TABLE IF NOT EXISTS friends
(
    user_id   INT,
    friend_id INT
);

CREATE TABLE IF NOT EXISTS likes
(
    user_id INT,
    film_id INT,
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (film_id) REFERENCES films (id),
    PRIMARY KEY (user_id, film_id)
);
